### ISSUE TITLE
npm start starts the app in development mode

### ISSUE THREAD

**Issue by kratsg** [deafchi/signsfive-web#29]
Need to allow for environment variable to override this -- especially for our staging server.

**Comment by meltedspork** [comment]
Stuff to read first: 
https://devcenter.heroku.com/articles/deploying-nodejs#specifying-a-start-script
https://devcenter.heroku.com/articles/node-best-practices
https://elements.heroku.com/buildpacks/nhutphuongit/create-react-app-buildpack

We thought `npm start` is to run either development, staging or production. But it turns out that `scripts/build` (production), `scripts/start`(development), and `scripts/test` (test) has their own of setting up website

**Comment by meltedspork** [comment]
@kratsg is this good to close now?
